# Generated by Django 5.2 on 2025-04-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_familymember_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': 'عضو الأسرة', 'verbose_name_plural': ' أعضاء أسرة ألمرشح'},
        ),
        migrations.AddField(
            model_name='familymember',
            name='note',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
    ]
