# Generated by Django 5.2 on 2025-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_person_family_members_familymember_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('father', 'أب'), ('mother', 'أم'), ('spouse', 'زوج/زوجة'), ('son', 'ابن'), ('daughter', 'ابنة'), ('brother', 'أخ'), ('sister', 'أخت'), ('other', 'أخرى')], default='other', max_length=15, verbose_name='صلة القرابة'),
        ),
    ]
