# Generated by Django 5.2 on 2025-05-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_familymember_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='+961', max_length=100, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
