# Generated by Django 5.2 on 2025-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_gallery_alter_familymember_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalqualification',
            name='year',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_year',
        ),
        migrations.AlterField(
            model_name='educationalqualification',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المؤسسة التعليمية'),
        ),
    ]
