# Generated by Django 5.2 on 2025-05-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_educationalqualification_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagramLink', models.TextField(blank=True, null=True)),
                ('facebookLink', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='setting/')),
                ('linkedinLink', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dev_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dev_img', models.ImageField(blank=True, null=True, upload_to='setting/')),
            ],
        ),
    ]
