# Generated by Django 5.2 on 2025-05-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_mysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='target_categories',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='main.category', verbose_name='الفئات المستهدفة للتحسين'),
        ),
    ]
