# Generated by Django 5.2 on 2025-05-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_person_target_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysetting',
            name='leyha_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mysetting',
            name='leyha_photo',
            field=models.ImageField(blank=True, null=True, upload_to='setting/'),
        ),
    ]
